apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-xss-demo
  labels:
    app: flask-xss-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-xss-demo
  template:
    metadata:
      labels:
        app: flask-xss-demo
    spec:
      containers:
        - name: flask-xss-demo
          
          image: setthapong/xs-app-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
